# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#   Mayor.create(name: 'Emanuel', city: cities.first)
apps = App.create([
  { name: 'LAST24',
    app_url: 'https://last24.herokuapp.com/',
    built_with: "Javascript, jQuery, CSS, HTML, Ruby on Rails, Heroku, Twitter APIs, Instagram APIs, Google Maps APIs, Zurb Foundation, MongoDB, OmniAuth, oAuth, Devise" ,
    snippet: "",
    description: "LAST24 merges your socials news feeds from your friends and people you follow into one single, elegantly designed timeline. All interactions will be contained with the side (like, comment, tweet) without ever having the need to navigate away to provider's website. 
LAST24 built with Javascript, CSS, HTML and Ruby on Rails using API from Twitter and Instagram (for content and oAuth). ",
    source_url: "https://github.com/RKim220/project4",
    thumbnail_url: ["https://s3-us-west-1.amazonaws.com/myportfolio.toan/last24_hand.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/l24.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/l24_timeline.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/l24_instagram.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/l24_feed.png"],
    like: 0,
    twitter: "One timeline to rule them all",
    hashtag: "whathappened"},
  { name: 'myBeautyCase',
    app_url: 'https://mybeautycase.herokuapp.com/',
    built_with: " Ruby On Rails, PaperClip, AWS S3 Storage, Heroku, jQuery, Bootstrap, HTML5, CSS, Javascript, MongoDB, b-crypt, Factual APIs, AWS Marketplace APIs",
    snippet: "",
    description: "Inspired by the idea of my wife who is struggled to keep her beauty products organized. myBeautyCase is my first Ruby on Rails app. Builtwith: Ruby On Rails (with gems like PaperClip), Web Brick server, Heroku app deployment, jQuery Bootstrap on the foundation of HTML5 and CSS. Extensive use of Factual's Consumer Products APIs were also used during this project to simplify the process of search for products.",
    source_url: "https://github.com/toannguyenle/makeupcase",
    thumbnail_url: ["https://s3-us-west-1.amazonaws.com/myportfolio.toan/bc_user_profile.png",
                     "https://s3-us-west-1.amazonaws.com/myportfolio.toan/mb_hand.png",
                     "https://s3-us-west-1.amazonaws.com/myportfolio.toan/bc_brand.png",
                     "https://s3-us-west-1.amazonaws.com/myportfolio.toan/bc_user_summary.png",
                     "https://s3-us-west-1.amazonaws.com/myportfolio.toan/bc_users.png"],
    like: 0,
    twitter: "It's time to organize your case",
    hashtag: "whereismystuff"},
  { name: 'feedme',
    app_url: 'https://feedmeapp.herokuapp.com/',
    built_with: "Ruby On Rails, AngularJS, Google Maps APIs, ORDR.in API, Yelp APIs, Bootstrap, Postgres, mySQL, HTML, CSS, Javascript" ,
    snippet: "",
    description: "For the undecided consumer, who may have limited budget and time, feedme is a service that assists users to quickly make dining decisions. Unlike Grubhub, Groupon or Yelp, feedMe provides an intuitive yet effortless experience. First project using Test Driven Development mantra. Using Rspec Testing with FactoryGirl and CapyBara, feedMe was built with: Ruby On Rails, AngularJS, Google Maps API, ORDR.in API, Yelp API, Bootstrap all inside a functional Single Page Application.",
    source_url: "https://github.com/toannguyenle/feedmeapp",
    thumbnail_url: ["https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_hand.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_order_with_movies.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_yelp.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_confirmation.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_order_page.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_order_summary.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_order_summary2.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_yelp_map.png"],
    like: 0,
    twitter: "Hungry? Let's order some food",
    hashtag: "hungry"},
  { name: 'my portfolio',
    app_url: 'http://toangular.com/',
    built_with: "Ruby On Rails, AngularJS, Zurb Foundation, jQuery, Javascript, HTML, CSS, Heroku, AWS" ,
    snippet: "",
    description: "I want to learn by building a simple portfolio page from scratch using mostly AngularJS and Ruby on Rails for the backend (served as API endpoints for my AngularJS services. The site features responsive design and quick search option using Angular filter directive.",
    source_url: "https://github.com/toannguyenle/myportfolio",
    thumbnail_url: ["https://s3-us-west-1.amazonaws.com/myportfolio.toan/port_hand.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/port_home.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/port_apps.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/port_1.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/port_contact"],
    like: 0,
    twitter: "Hungry? Let's order some food",
    hashtag: "hungry"},
  { name: 'Social Tic',
    app_url: 'https://tttcg.firebaseapp.com/',
    built_with: "AngularJS, Firebase, Javascript, HTML, CSS" ,
    snippet: "",
    description: "For this project, chat was synced in real time using Firebase technology as well as real time heat map from users that area accessing the sites (up to 50 at any time.
'Social Tic' was my first playground in term of making multiple technology such as AngularJS works with Firebase and the traditional Javascript.",
    source_url: "https://github.com/toannguyenle/tictactoe/tree/master/ver3.0production",
    thumbnail_url: ["https://s3-us-west-1.amazonaws.com/myportfolio.toan/ttt_board.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/ttt_welcome.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/ttt_chat.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/ttt_game.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/ttt_screen.png"
                    ],
    like: 0,
    twitter: "Let's play some Tic Tac Toe",
    hashtag: "tictactoe"},
  { name: 'fandango discovery',
    app_url: 'http://fandangodiscover.herokuapp.com/',
    built_with: "Ruby On Rails, Bootstrap, Javascript, HTML, CSS, Heroku, fandago APIs" ,
    snippet: "",
    description: "Built within 24 hours of 2014 NBC Universal Hackathon. fandago discover aims to gamify the movie going experience by providing fans more engagement with contents and more intereactions as well as rewards with each movie going and watching.",
    source_url: "https://github.com/toannguyenle/FandangoDiscover-Mock",
    thumbnail_url: ["https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_home.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_logo.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_1.png",
                    "https://s3-us-west-1.amazonaws.com/myportfolio.toan/fm_2.png"],
    like: 0,
    twitter: "What's showing right now?",
    hashtag: "showtime"}
   ])